AllCops:
  Exclude:      
    - 'db/**/*'
    - 'bin/*'
    - 'config/*'
    - 'config/**/*'   
    - 'lib/*'
    - 'log/*'
    - 'node_modules/**/*'
    - 'test/**/*'
    - 'public/*'
    - 'vendor/**/*'
    - 'Gemfile'

  TargetRubyVersion: 2.6
  
Style/FrozenStringLiteralComment:
  Enabled: false
  
Metrics/LineLength:
  Max: 105

Style/Documentation:
  Enabled: false
