development:
  stripe_secret_key: sk_test_51ILaC8GJiMymBHNvi8RlFsDizRICikoLvZMaGgweZ01eB4g8nHAQuLkhMbBKL9U4WCFrHw5w24BChMjxNmOnSgUY00xjUrcAnq
  stripe_publishable_key: pk_test_51ILaC8GJiMymBHNvD9kcNnQn7r7sD5P5S2oHMO6sM9FmrhDsxheuiwpQfJjSzye9WeBBnoXac41FIysz0Q8dceQE00ORpixt1r
